import { memo } from "react";

/*
 * Icons are real pixel art: each one is a 16x16 character grid mapped through a
 * palette and emitted as <rect> runs. Horizontal runs of the same colour collapse
 * into a single rect, which keeps the SVG small enough to inline everywhere.
 */

const PALETTE: Record<string, string> = {
  ".": "",
  b: "#0000ff",
  c: "#00ffff",
  d: "#808080", // shadow
  e: "#e0e0e0",
  f: "#f0f0f0",
  g: "#c0c0c0", // face
  G: "#008000",
  k: "#000000", // outline
  L: "#00ff00",
  m: "#c0c0ff",
  n: "#000080", // navy
  o: "#ff8000",
  p: "#800080",
  r: "#a80000",
  R: "#ff0000",
  s: "#dfdfdf", // light face
  t: "#008080", // teal
  w: "#ffffff", // highlight
  y: "#ffff00", // folder yellow
  Y: "#808000", // folder shade
};

const GRIDS: Record<string, string[]> = {
  airflow: [
    "................",
    "......ttt.......",
    ".....ttttt......",
    "....tt...tt.....",
    "...tt.....tt....",
    "..tt..GGG..tt...",
    "..t..GGGGG..t...",
    "..t..GGGGG..t...",
    "..tt..GGG..tt...",
    "...tt.....tt....",
    "....tt...tt.....",
    ".....ttttt......",
    "......ttt.......",
    "................",
    "................",
    "................",
  ],
  clippy: [
    "................",
    "....kkkkkk......",
    "...kddddddk.....",
    "..kdd....ddk....",
    "..kd.kkkk.dk....",
    "..kd.k..k.dk....",
    "..kd.k..k.dk....",
    "..kd.k..k.dk....",
    "..kd.k..k.dk....",
    "...kd.k.kdk.....",
    "....kd.kdk......",
    ".....kddk.......",
    "......kk........",
    "................",
    "................",
    "................",
  ],
  computer: [
    "................",
    ".kkkkkkkkkkkk...",
    ".kwsssssssssk...",
    ".kwtnnnnnnnsk...",
    ".kwtnccccnnsk...",
    ".kwtnnnnnnnsk...",
    ".kwtnnnnnnnsk...",
    ".kwsssssssssk...",
    ".kddddddddddk...",
    "..kkkkkkkkkk....",
    "..kgggggggggk...",
    ".kwgLkgggggdk...",
    ".kddddddddddgk..",
    "..kkkkkkkkkkk...",
    "................",
    "................",
  ],
  controlpanel: [
    "................",
    "..kkkkkkkkkkk...",
    "..kwsssssssdk...",
    "..kwgkkkkkgdk...",
    "..kwgkrrrkgdk...",
    "..kwgkkkkkgdk...",
    "..kwgggggggdk...",
    "..kwgkgkgkgdk...",
    "..kwgkgkgkgdk...",
    "..kwgLgkgLgdk...",
    "..kwgkgkgkgdk...",
    "..kwgggggggdk...",
    "..kdddddddddk...",
    "..kkkkkkkkkkk...",
    "................",
    "................",
  ],
  defrag: [
    "................",
    ".kkkkkkkkkkkkk..",
    ".kwwwwwwwwwwwk..",
    ".kwnnnnGGrrwwk..",
    ".kwnnnGGrrwwwk..",
    ".kwnnGGrrwwwwk..",
    ".kwnnnGGrwwwwk..",
    ".kwnnnnGGrrwwk..",
    ".kwnnGGGGrrwwk..",
    ".kwnnnnnGGrwwk..",
    ".kwnnnnGGrrwwk..",
    ".kwwwwwwwwwwwk..",
    ".kddddddddddddk.",
    ".kkkkkkkkkkkkk..",
    "................",
    "................",
  ],
  "drive-hdd": [
    "................",
    "................",
    "..kkkkkkkkkkkk..",
    ".kwsssssssssssk.",
    ".kwggggggggggdk.",
    ".kwggggggggggdk.",
    ".kwggggggggggdk.",
    ".kddddddddddddk.",
    ".kwsssssssssssk.",
    ".kwgggggggggggk.",
    ".kwgg.....LkGdk.",
    ".kwgg......kGdk.",
    ".kddddddddddddk.",
    "..kkkkkkkkkkkk..",
    "................",
    "................",
  ],
  eventlog: [
    "................",
    "..kkkkkkkkkkk...",
    "..kwsssssssdk...",
    "..kwgggggggdk...",
    "..kwgRRRRRgdk...",
    "..kwgggggggdk...",
    "..kwgyyyyygdk...",
    "..kwgggggggdk...",
    "..kwgLLLLLgdk...",
    "..kwgggggggdk...",
    "..kwgnnnnngdk...",
    "..kwgggggggdk...",
    "..kdddddddddk...",
    "..kkkkkkkkkkk...",
    "................",
    "................",
  ],
  file: [
    "................",
    "..kkkkkkkk......",
    "..kwwwwwwkk.....",
    "..kwwwwwwkwk....",
    "..kwwwwwwkkkk...",
    "..kwwwwwwwwwk...",
    "..kwwwwwwwwwk...",
    "..kwwwwwwwwwk...",
    "..kwwwwwwwwwk...",
    "..kwwwwwwwwwk...",
    "..kwwwwwwwwwk...",
    "..kwwwwwwwwwk...",
    "..kwwwwwwwwwk...",
    "..kkkkkkkkkkk...",
    "................",
    "................",
  ],
  "file-json": [
    "................",
    "..kkkkkkkk......",
    "..kwwwwwwkk.....",
    "..kwwwwwwkwk....",
    "..kwwwwwwkkkk...",
    "..kw.kw.wkwwk...",
    "..kwk..k.wwwk...",
    "..kwk..k.wwwk...",
    "..kwk..k.wwwk...",
    "..kw.kw..wwwk...",
    "..kwwwwwwwwwk...",
    "..kwppppppwwk...",
    "..kwwwwwwwwwk...",
    "..kkkkkkkkkkk...",
    "................",
    "................",
  ],
  "file-log": [
    "................",
    "..kkkkkkkk......",
    "..kwwwwwwkk.....",
    "..kwwwwwwkwk....",
    "..kwwwwwwkkkk...",
    "..kwddddddddk...",
    "..kwwwwwwwwwk...",
    "..kwdddddddwk...",
    "..kwwwwwwwwwk...",
    "..kwddddddddk...",
    "..kwwwwwwwwwk...",
    "..kwdddddwwwk...",
    "..kwwwwwwwwwk...",
    "..kkkkkkkkkkk...",
    "................",
    "................",
  ],
  "file-py": [
    "................",
    "..kkkkkkkk......",
    "..kwwwwwwkk.....",
    "..kwwwwwwkwk....",
    "..kwwwwwwkkkk...",
    "..kwnnnnwwwwk...",
    "..kwn..nwwwwk...",
    "..kwnnnnwwwwk...",
    "..kwn...wyyyk...",
    "..kwn..yyyyyk...",
    "..kwwwyyy.yyk...",
    "..kwwwyyyyyyk...",
    "..kwwwwwyyyyk...",
    "..kkkkkkkkkkk...",
    "................",
    "................",
  ],
  find: [
    "................",
    "....kkkk........",
    "...kcccck.......",
    "..kcwwwwck......",
    "..kcwwwwck......",
    "..kcwwwwck......",
    "...kcccck.......",
    "....kkkkkk......",
    ".......kkkk.....",
    "........kkkk....",
    ".........kkkk...",
    "..........kkk...",
    "................",
    "................",
    "................",
    "................",
  ],
  folder: [
    "................",
    "................",
    "..kkkk..........",
    ".kyyyyk.........",
    ".kyyyyykkkkkkk..",
    ".kyyyyyyyyyyyk..",
    ".kyyyyyyyyyyyk..",
    ".kyyyyyyyyyyyk..",
    ".kyyyyyyyyyyyk..",
    ".kyyyyyyyyyyyk..",
    ".kyyyyyyyyyyyk..",
    ".kYYYYYYYYYYYk..",
    ".kYYYYYYYYYYYk..",
    "..kkkkkkkkkkk...",
    "................",
    "................",
  ],
  "folder-open": [
    "................",
    "................",
    "..kkkk..........",
    ".kyyyyk.........",
    ".kyyyyykkkkkkk..",
    ".kyyyyyyyyyyyk..",
    ".kyyyyyyyyyyyk..",
    ".kkkkkkkkkkkkk..",
    ".kwwwwwwwwwwkk..",
    "kwyyyyyyyyyyk...",
    "kyyyyyyyyyyk....",
    "kyyyyyyyyyyk....",
    ".kYYYYYYYYk.....",
    "..kkkkkkkk......",
    "................",
    "................",
  ],
  help: [
    "................",
    "....kkkkkkk.....",
    "...kwwwwwwwk....",
    "..kwwnnnnnwwk...",
    "..kwnnwwwnnwk...",
    "..kwnnwwwnnwk...",
    "..kwwwwwnnwwk...",
    "..kwwwwnnwwwk...",
    "..kwwwnnwwwwk...",
    "..kwwwnnwwwwk...",
    "..kwwwwwwwwwk...",
    "..kwwwnnwwwwk...",
    "..kwwwnnwwwwk...",
    "...kwwwwwwwk....",
    "....kkkkkkk.....",
    "................",
  ],
  mailbox: [
    "................",
    "................",
    ".kkkkkkkkkkkkk..",
    ".kwwwwwwwwwwwk..",
    ".kwkwwwwwwwkwk..",
    ".kwwkwwwwwkwwk..",
    ".kwwwkwwwkwwwk..",
    ".kwwwwkwkwwwwk..",
    ".kwwwwwkwwwwwk..",
    ".kwwwwkwkwwwwk..",
    ".kwwwkwwwkwwwk..",
    ".kwwkwwwwwkwwk..",
    ".kwkwwwwwwwkwk..",
    ".kddddddddddddk.",
    ".kkkkkkkkkkkkk..",
    "................",
  ],
  "mailbox-full": [
    "................",
    "................",
    ".kkkkkkkkkkkkk..",
    ".kwwwwwwwwwwwk..",
    ".kwkwwwwwwwkwk..",
    ".kwwkwwwwwkwwk..",
    ".kwwwkwwwkwwwk..",
    ".kwwwwkwkwwwwk..",
    ".kRRRRRkRRRRRk..",
    ".kRRRRkwkRRRRk..",
    ".kRRRkwwwkRRRk..",
    ".kRRkwwwwwkRRk..",
    ".kRkwwwwwwwkRk..",
    ".kddddddddddddk.",
    ".kkkkkkkkkkkkk..",
    "................",
  ],
  mine: [
    "................",
    "................",
    "......k.k.......",
    ".......k........",
    "...k.kkkkk.k....",
    "....kkkkkkk.....",
    "...kkkwkkkkk....",
    "..kkkkkkkkkkk...",
    "..kkkkkkkkkkk...",
    "..kkkkkkkkkkk...",
    "...kkkkkkkkk....",
    "....kkkkkkk.....",
    "...k.kkkkk.k....",
    "................",
    "................",
    "................",
  ],
  network: [
    "................",
    "kkkkkkk.........",
    "kwsssdk.........",
    "kwnnndk.........",
    "kwsssdk.kkkkkkk.",
    "kddddgk.kwsssdk.",
    ".kkkkk..kwnnndk.",
    "...k....kwsssdk.",
    "...kkkkkkddddgk.",
    "........kkkkkk..",
    "...k......k.....",
    "...kkkkkkkk.....",
    "................",
    "................",
    "................",
    "................",
  ],
  notepad: [
    "................",
    "..kkkkkkkkkk....",
    "..kwwwwwwwwk....",
    "..kwnnnnnnwk....",
    "..kwwwwwwwwk....",
    "..kwkkkkkkwk....",
    "..kwwwwwwwwk....",
    "..kwkkkkkkwk....",
    "..kwwwwwwwwk....",
    "..kwkkkkkkwk....",
    "..kwwwwwwwwk....",
    "..kwkkkkwwwk....",
    "..kwwwwwwwwk....",
    "..kkkkkkkkkk....",
    "................",
    "................",
  ],
  paint: [
    "................",
    "............kk..",
    "...........kwwk.",
    "....kkkkk..kwwk.",
    "..kkyyyyykkkwk..",
    ".kyyyRyyyyykk...",
    ".kyyyyyyGyykk...",
    ".kyyyyyyyykddk..",
    ".kybyyyyyyyyyk..",
    ".kyyyyy.kyyyyk..",
    ".kyyyyy..kyyyk..",
    "..kyyyyy.yyyk...",
    "...kyyyyyyyk....",
    "....kkkkkkk.....",
    "................",
    "................",
  ],
  "recycle-empty": [
    "................",
    "....kkkkkkkk....",
    "...kwwwwwwwwk...",
    "...kwkkkkkkwk...",
    "..kkkkkkkkkkkk..",
    "..kwGGGGGGGGwk..",
    "..kwGkGkGkGGwk..",
    "..kwGkGkGkGGwk..",
    "...kGkGkGkGGk...",
    "...kGkGkGkGGk...",
    "...kGkGkGkGGk...",
    "....kGGGGGGk....",
    "....kGGGGGGk....",
    ".....kkkkkk.....",
    "................",
    "................",
  ],
  "recycle-full": [
    "................",
    "......yy.o......",
    "....kkkkkkkk....",
    "...kwwyywwoyk...",
    "...kwkkkkkkwk...",
    "..kkkkkkkkkkkk..",
    "..kwGGGGGGGGwk..",
    "..kwGkGkGkGGwk..",
    "..kwGkGkGkGGwk..",
    "...kGkGkGkGGk...",
    "...kGkGkGkGGk...",
    "...kGkGkGkGGk...",
    "....kGGGGGGk....",
    "....kGGGGGGk....",
    ".....kkkkkk.....",
    "................",
  ],
  run: [
    "................",
    "..kkkkkkkkkkk...",
    "..knnnnnnnnnk...",
    "..kwwwwwwwwwk...",
    "..kwwwwwwwwwk...",
    "..kwww.k.wwwk...",
    "..kwww.kk.wwk...",
    "..kwGGGGGkwwk...",
    "..kwGGGGGGkwk...",
    "..kwGGGGGkwwk...",
    "..kwww.kk.wwk...",
    "..kwww.k.wwwk...",
    "..kwwwwwwwwwk...",
    "..kkkkkkkkkkk...",
    "................",
    "................",
  ],
  scheduler: [
    "................",
    "....kkkkkkk.....",
    "...kwwwwwwwk....",
    "..kwwwkwwwwwk...",
    "..kwwwkwwwwwk...",
    ".kwwwwkwwwwwwk..",
    ".kwwwwkwwwwwwk..",
    ".kwwwwkkkkwwwk..",
    ".kwwwwwwwwwwwk..",
    ".kwwwwwwwwwwwk..",
    "..kwwwwwwwwwk...",
    "..kwwwwwwwwwk...",
    "...kwwwwwwwk....",
    "....kkkkkkk.....",
    "................",
    "................",
  ],
  shutdown: [
    "................",
    "................",
    "......kkk.......",
    ".....kwwwk......",
    "...kkkwwwkkk....",
    "..kwrk.k.krwk...",
    "..kwrk.k.krwk...",
    ".kwrrk.k.krrwk..",
    ".kwrrkkkkkrrwk..",
    ".kwrrrrrrrrrwk..",
    "..kwrrrrrrrwk...",
    "..kkwrrrrrwkk...",
    "....kkkkkkk.....",
    "................",
    "................",
    "................",
  ],
  speaker: [
    "................",
    "................",
    "..........k.....",
    ".......k...k....",
    "....kkk.k...k...",
    "...kkkk.....k...",
    "kkkkkkk.k.k.k...",
    "kkkkkkk.k.k.k...",
    "kkkkkkk.k.k.k...",
    "kkkkkkk.k.k.k...",
    "...kkkk.....k...",
    "....kkk.k...k...",
    ".......k...k....",
    "..........k.....",
    "................",
    "................",
  ],
  "speaker-muted": [
    "................",
    "................",
    "................",
    "................",
    "....kkk.........",
    "...kkkk.r...r...",
    "kkkkkkk..r.r....",
    "kkkkkkk...r.....",
    "kkkkkkk..r.r....",
    "kkkkkkk.r...r...",
    "...kkkk.........",
    "....kkk.........",
    "................",
    "................",
    "................",
    "................",
  ],
  taskmgr: [
    "................",
    ".kkkkkkkkkkkkk..",
    ".knnnnnnnnnnnk..",
    ".kgggggggggggk..",
    ".kkkkkkkkkkkkk..",
    ".kk.........kk..",
    ".kk....L....kk..",
    ".kk...LL..L.kk..",
    ".kk..LLL.LL.kk..",
    ".kk.LLLLLLL.kk..",
    ".kkLLLLLLLL.kk..",
    ".kkkkkkkkkkkkk..",
    ".kgggggggggggk..",
    ".kkkkkkkkkkkkk..",
    "................",
    "................",
  ],
  terminal: [
    "................",
    ".kkkkkkkkkkkkk..",
    ".kgggggggggggk..",
    ".kkkkkkkkkkkkk..",
    ".kkkkkkkkkkkkk..",
    ".kk.........kk..",
    ".kkLL.L.....kk..",
    ".kk..L......kk..",
    ".kkLL.L.....kk..",
    ".kk.........kk..",
    ".kkL........kk..",
    ".kkkkkkkkkkkkk..",
    ".kgggggggggggk..",
    ".kkkkkkkkkkkkk..",
    "................",
    "................",
  ],
};

// 32x32 dialog glyphs, drawn as scaled 16x16 art with a bolder palette.
const DIALOG: Record<string, string[]> = {
  error: [
    "................",
    ".....kkkkkk.....",
    "...kkrrrrrrkk...",
    "..krrrrrrrrrrk..",
    ".krrrrrrrrrrrrk.",
    ".krrwwrrrrwwrrk.",
    "krrrwwrrrrwwrrrk",
    "krrrrwwrrwwrrrrk",
    "krrrrrwwwwrrrrrk",
    "krrrrrwwwwrrrrrk",
    "krrrrwwrrwwrrrrk",
    "krrrwwrrrrwwrrrk",
    ".krrwwrrrrwwrrk.",
    ".krrrrrrrrrrrrk.",
    "..kkrrrrrrrrkk..",
    "....kkkkkkkk....",
  ],
  info: [
    "................",
    ".....kkkkkk.....",
    "...kknnnnnnkk...",
    "..knnnnnnnnnnk..",
    ".knnnnwwwwnnnnk.",
    ".knnnnwwwwnnnnk.",
    "knnnnnnnnnnnnnnk",
    "knnnnwwwwwnnnnnk",
    "knnnnnnwwwnnnnnk",
    "knnnnnnwwwnnnnnk",
    "knnnnnnwwwnnnnnk",
    "knnnnwwwwwwwnnnk",
    ".knnnnnnnnnnnnk.",
    ".knnnnnnnnnnnnk.",
    "..kknnnnnnnnkk..",
    "....kkkkkkkk....",
  ],
  question: [
    "................",
    ".....kkkkkk.....",
    "...kknnnnnnkk...",
    "..knnnnnnnnnnk..",
    ".knnnwwwwwwnnnk.",
    ".knnwwnnnnwwnnk.",
    "knnnwwnnnnwwnnnk",
    "knnnnnnnnnwwnnnk",
    "knnnnnnnnwwnnnnk",
    "knnnnnnnwwnnnnnk",
    "knnnnnnwwnnnnnnk",
    "knnnnnnnnnnnnnnk",
    ".knnnnnwwnnnnnk.",
    ".knnnnnwwnnnnnk.",
    "..kknnnnnnnnkk..",
    "....kkkkkkkk....",
  ],
  warning: [
    "................",
    ".......kk.......",
    "......kyyk......",
    "......kyyk......",
    ".....kyyyyk.....",
    ".....kykkyk.....",
    "....kyykkyyk....",
    "....kyykkyyk....",
    "...kyyykkyyyk...",
    "...kyyykkyyyk...",
    "..kyyyykkyyyyk..",
    "..kyyyyyyyyyyk..",
    ".kyyyyykkyyyyyk.",
    ".kyyyyykkyyyyyk.",
    "kyyyyyyyyyyyyyyk",
    ".kkkkkkkkkkkkkk.",
  ],
};

const ALL: Record<string, string[]> = { ...GRIDS, ...DIALOG };

/** Collapse each row into horizontal runs so one <rect> covers many pixels. */
function runs(grid: string[]) {
  const out: { x: number; y: number; w: number; fill: string }[] = [];
  grid.forEach((row, y) => {
    let x = 0;
    while (x < row.length) {
      const ch = row[x] ?? ".";
      const fill = PALETTE[ch] ?? "";
      if (!fill) {
        x += 1;
        continue;
      }
      let w = 1;
      while (x + w < row.length && row[x + w] === ch) w += 1;
      out.push({ fill, w, x, y });
      x += w;
    }
  });
  return out;
}

const CACHE = new Map<string, ReturnType<typeof runs>>();

function getRuns(name: string) {
  let cached = CACHE.get(name);
  if (!cached) {
    cached = runs(ALL[name] ?? ALL.file ?? []);
    CACHE.set(name, cached);
  }
  return cached;
}

export type IconName = keyof typeof ALL | string;

export const Icon = memo(function Icon({
  className,
  name,
  size = 16,
}: {
  readonly name: IconName;
  readonly size?: number;
  readonly className?: string;
}) {
  return (
    <svg
      aria-hidden="true"
      className={`aos-icon${className ? ` ${className}` : ""}`}
      height={size}
      viewBox="0 0 16 16"
      width={size}
      xmlns="http://www.w3.org/2000/svg"
    >
      {getRuns(String(name)).map((r, index) => (
        <rect fill={r.fill} height={1} key={index} width={r.w} x={r.x} y={r.y} />
      ))}
    </svg>
  );
});
